Make it easier to override auto-detected options in simple-build-and-install.

diff --git a/simple-build-and-install b/simple-build-and-install
--- a/simple-build-and-install
+++ b/simple-build-and-install
@@ -1,6 +1,12 @@
 #!/bin/bash
 # Run this if you just want to build and install the program and you don't care about all the details.
 # Any additional arguments will be passed on to 'cmake'.
+# The following environment variables can be set to TRUE or FALSE to override the auto-detected values:
+#  - ENABLE_32BIT_GLINJECT
+#  - ENABLE_X86_ASM
+#  - ENABLE_FFMPEG_VERSIONS
+#  - WITH_QT5
+#  - WITH_GLINJECT
 
 set -e
 cd "$( dirname "${BASH_SOURCE[0]}" )"
@@ -12,61 +18,67 @@ fi
 
 export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig"
 
-echo "Detecting architecture ..."
-case "$( uname -m )" in
-	"i386"|"i486"|"i586"|"i686")
-		ENABLE_32BIT_GLINJECT="FALSE"
-		ENABLE_X86_ASM="TRUE"
-		WITH_GLINJECT="TRUE"
-		;;
-	"x86_64")
-		ENABLE_32BIT_GLINJECT="TRUE"
-		ENABLE_X86_ASM="TRUE"
-		WITH_GLINJECT="TRUE"
-		;;
-	*)
-		ENABLE_32BIT_GLINJECT="FALSE"
-		ENABLE_X86_ASM="FALSE"
-		WITH_GLINJECT="FALSE"
-		;;
-esac
-
-echo "Detecting ffmpeg/libav ..."
-if ! pkg-config --exists libavcodec; then
-	echo "  Error: libavcodec development package not found, make sure ffmpeg or libav development packages are installed."
-	exit 1
-fi
-LIBAVCODEC_INCLUDE_DIR=`pkg-config --variable=includedir libavcodec`
-HAS_FFMPEG=$( grep -c "This file is part of FFmpeg." $LIBAVCODEC_INCLUDE_DIR/libavcodec/avcodec.h || true )
-HAS_LIBAV=$( grep -c "This file is part of Libav." $LIBAVCODEC_INCLUDE_DIR/libavcodec/avcodec.h || true )
-if [ $HAS_FFMPEG -gt 0 ]; then
-	if [ $HAS_LIBAV -gt 0 ]; then
-		echo "  Error: Detected ffmpeg AND libav, this should not happen!"
-		exit 1
-	else
-		echo "  Detected ffmpeg."
-		ENABLE_FFMPEG_VERSIONS="TRUE"
-	fi
-else
-	if [ $HAS_LIBAV -gt 0 ]; then
-		echo "  Detected libav."
-		ENABLE_FFMPEG_VERSIONS="FALSE"
-	else
-		echo "  Error: Detection failed."
-		exit 1
-	fi
+if [ -z "$ENABLE_32BIT_GLINJECT" ] || [ -z "$ENABLE_X86_ASM" ] || [ -z "$WITH_GLINJECT" ]; then
+	echo "Detecting architecture ..."
+	case "$( uname -m )" in
+		"i386"|"i486"|"i586"|"i686")
+			: ${ENABLE_32BIT_GLINJECT:="FALSE"}
+			: ${ENABLE_X86_ASM:="TRUE"}
+			: ${WITH_GLINJECT:="TRUE"}
+			;;
+		"x86_64")
+			: ${ENABLE_32BIT_GLINJECT:="TRUE"}
+			: ${ENABLE_X86_ASM:="TRUE"}
+			: ${WITH_GLINJECT:="TRUE"}
+			;;
+		*)
+			: ${ENABLE_32BIT_GLINJECT:="FALSE"}
+			: ${ENABLE_X86_ASM:="FALSE"}
+			: ${WITH_GLINJECT:="FALSE"}
+			;;
+	esac
 fi
 
-echo "Detecting Qt version ..."
-if pkg-config --exists Qt5Gui; then
-	echo "  Detected Qt5."
-	WITH_QT5="TRUE"
-elif pkg-config --exists QtGui; then
-	echo "  Detected Qt4."
-	WITH_QT5="FALSE"
-else
-	echo "  Error: Qt development package not found."
-	exit 1
+if [ -z "$ENABLE_FFMPEG_VERSIONS" ]; then
+	echo "Detecting ffmpeg/libav ..."
+	if ! pkg-config --exists libavcodec; then
+		echo "  Error: libavcodec development package not found, make sure ffmpeg or libav development packages are installed."
+		exit 1
+	fi
+	LIBAVCODEC_INCLUDE_DIR=`pkg-config --variable=includedir libavcodec`
+	HAS_FFMPEG=$( grep -c "This file is part of FFmpeg." $LIBAVCODEC_INCLUDE_DIR/libavcodec/avcodec.h || true )
+	HAS_LIBAV=$( grep -c "This file is part of Libav." $LIBAVCODEC_INCLUDE_DIR/libavcodec/avcodec.h || true )
+	if [ $HAS_FFMPEG -gt 0 ]; then
+		if [ $HAS_LIBAV -gt 0 ]; then
+			echo "  Error: Detected ffmpeg AND libav, this should not happen!"
+			exit 1
+		else
+			echo "  Detected ffmpeg."
+			ENABLE_FFMPEG_VERSIONS="TRUE"
+		fi
+	else
+		if [ $HAS_LIBAV -gt 0 ]; then
+			echo "  Detected libav."
+			ENABLE_FFMPEG_VERSIONS="FALSE"
+		else
+			echo "  Error: Detection failed."
+			exit 1
+		fi
+	fi
+fi
+
+if [ -z "$WITH_QT5" ]; then
+	echo "Detecting Qt version ..."
+	if pkg-config --exists Qt5Gui; then
+		echo "  Detected Qt5."
+		WITH_QT5="TRUE"
+	elif pkg-config --exists QtGui; then
+		echo "  Detected Qt4."
+		WITH_QT5="FALSE"
+	else
+		echo "  Error: Qt development package not found."
+		exit 1
+	fi
 fi
 
 echo "Auto-detected options:"
@@ -76,11 +88,18 @@ echo "  ENABLE_FFMPEG_VERSIONS = $ENABLE_FFMPEG_VERSIONS"
 echo "  WITH_QT5 = $WITH_QT5"
 echo "  WITH_GLINJECT = $WITH_GLINJECT"
 
+if [ x"$WITH_QT5" == x"TRUE" ]; then
+	AUTOMOC_BUG_WORKAROUND=""
+else
+	AUTOMOC_BUG_WORKAROUND="-DCMAKE_AUTOMOC_MOC_OPTIONS=\"-D_SYS_SYSMACROS_H_OUTER\""
+fi
+
 PREFIX="/usr"
-OPTIONS="-DENABLE_32BIT_GLINJECT=$ENABLE_32BIT_GLINJECT -DENABLE_X86_ASM=$ENABLE_X86_ASM -DENABLE_FFMPEG_VERSIONS=$ENABLE_FFMPEG_VERSIONS -DWITH_QT5=$WITH_QT5 -DWITH_GLINJECT=$WITH_GLINJECT"
+OPTIONS="-DENABLE_32BIT_GLINJECT=$ENABLE_32BIT_GLINJECT -DENABLE_X86_ASM=$ENABLE_X86_ASM -DENABLE_FFMPEG_VERSIONS=$ENABLE_FFMPEG_VERSIONS -DWITH_QT5=$WITH_QT5 -DWITH_GLINJECT=$WITH_GLINJECT $AUTOMOC_BUG_WORKAROUND"
 
 echo "Entering build-release directory ..."
-mkdir -p build-release
+rm -rf build-release
+mkdir build-release
 cd build-release
 
 echo "Running cmake ..."
