Small change to simple-build-and-install: check whether ffmpeg/libav exists before doing tests.

diff --git a/simple-build-and-install b/simple-build-and-install
--- a/simple-build-and-install
+++ b/simple-build-and-install
@@ -7,11 +7,15 @@
 set -e
 
 if [ x"$( whoami )" = x"root" ]; then
-	echo "error: don't run this script as root, this will mess up file permissions"
+	echo "Error: don't run this script as root, this will mess up file permissions"
 	exit 1
 fi
 
 echo "Detecting ffmpeg/libav ..."
+if [ ! -f /usr/include/libavcodec/avcodec.h ]; then
+	echo "Error: libavcodec header not found, make sure that ffmpeg or libav is installed."
+	exit 1
+fi
 HAS_FFMPEG=$( grep -c "This file is part of FFmpeg." /usr/include/libavcodec/avcodec.h || true )
 HAS_LIBAV=$( grep -c "This file is part of Libav." /usr/include/libavcodec/avcodec.h || true )
 if [ $HAS_FFMPEG -gt 0 ]; then
