Added glinject channels, improved permissions, added RMS level to AudioPreviewer, and restored fences in LockFreeMessageQueue and SSRVideoStream.

diff --git a/scripts/ssr-glinject b/scripts/ssr-glinject
--- a/scripts/ssr-glinject
+++ b/scripts/ssr-glinject
@@ -3,24 +3,25 @@
 set -e
 
 usage() {
-	echo "Usage: ssr-glinject [OPTIONS] [--] COMMAND"
-	echo ""
-	echo "Options:"
-	echo "  --help              Show this help message."
-	echo "  --glx-debug          Enables GLX debugging. This may reduce the performance"
-	echo "                       and print lots of error messages, but it is useful to"
-	echo "                       track down bugs."
-	echo "  --relax-permissions  Uses mode 666 instead of 600 for shared memory, so that"
-	echo "                       other users can record the stream. This is insecure and"
-	echo "                       should not be used on a computer that can be accessed by"
-	echo "                       other users that you don't trust."
-	echo ""
-	echo "This script uses LD_PRELOAD to inject the GLInject library into the given"
-	echo "command, so that SimpleScreenRecorder can record it. It should be safe to use"
-	echo "this on all applications (including command-line programs and shell scripts)."
-	echo "If the program doesn't use OpenGL, it should have no effect. If you find a"
-	echo "program that crashes or behaves incorrectly when GLInject is used, please submit"
-	echo "a bug report."
+	echo "Usage: ssr-glinject [OPTIONS] [--] COMMAND" >& 2
+	echo "" >& 2
+	echo "Options:" >& 2
+	echo "  --help               Show this help message." >& 2
+	echo "  --glx-debug          Enables GLX debugging. This may reduce the performance" >& 2
+	echo "                       and print lots of error messages, but it is useful to" >& 2
+	echo "                       track down bugs." >& 2
+	echo "  --relax-permissions  Uses mode 666 instead of 600 for shared memory, so that" >& 2
+	echo "                       other users can record the stream. This is insecure and" >& 2
+	echo "                       should not be used on a computer that can be accessed by" >& 2
+	echo "                       other users that you don't trust." >& 2
+	echo "  --channel=CHANNEL    Channel name to use. The default is 'channel-USERNAME'." >& 2
+	echo "" >& 2
+	echo "This script uses LD_PRELOAD to inject the GLInject library into the given" >& 2
+	echo "command, so that SimpleScreenRecorder can record it. It should be safe to use" >& 2
+	echo "this on all applications (including command-line programs and shell scripts)." >& 2
+	echo "If the program doesn't use OpenGL, it should have no effect. If you find a" >& 2
+	echo "program that crashes or behaves incorrectly when GLInject is used, please submit" >& 2
+	echo "a bug report." >& 2
 }
 
 export SSR_GLX_DEBUG=0
@@ -43,6 +44,10 @@ do
 	elif [ x"$1" = x"--relax-permissions" ]
 	then
 		export SSR_STREAM_RELAX_PERMISSIONS=1
+		shift
+	elif [ x"${1:0:10}" = x"--channel=" ]
+	then
+		export SSR_CHANNEL="${1:10}"
 		shift
 	elif [ x"${1:0:1}" = x"-" ]
 	then
